INSERT INTO NavigationItem (ID, PARENT_ID, SPRINGVIEWNAME, NAME) VALUES (1, NULL , NULL , 'MAIN');
INSERT INTO NavigationItem (ID, PARENT_ID, SPRINGVIEWNAME, NAME) VALUES (2, 1 , NULL , 'SUB');

INSERT INTO GROUPS (ID, NAME) VALUES (1, 'demogroup');
INSERT INTO USERS (ID, NAME, PRENAME, EMAIL, LOGIN, PASSWORD, GROUPS_ID) VALUES (1, 'DEMO', 'USER', 'demo@user.com', 'demouser', 'demouser', 1);


INSERT INTO MENU_MODEL (ID, LABEL ) VALUES (1, 'Start');
INSERT INTO MENU_MODEL (ID, LABEL, PARENT , CLASSSTRING) VALUES (2, 'Demo', 1, 'appointmentEditPresenter');

INSERT INTO GROUPS_MENU (ID, GROUPS_ID, MENUMODEL_ID, ACTIV) VALUES (1, 1, 1, 1);
INSERT INTO GROUPS_MENU (ID, GROUPS_ID, MENUMODEL_ID, ACTIV) VALUES (2, 1, 2, 1);

